CREATE TABLE tb_medico (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   nome VARCHAR(150) NOT NULL,
   telefone VARCHAR(11) NOT NULL,
   crm VARCHAR(20) NOT NULL UNIQUE,
   cpf VARCHAR(11) NOT NULL UNIQUE,
   email VARCHAR(150) NOT NULL UNIQUE,
   ativo BOOLEAN NOT NULL DEFAULT TRUE,
   data_nascimento DATE NOT NULL,
   data_cadastro DATETIME NOT NULL
);
